nodeLinker: pnp
npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  jest-preset-angular@*:
    dependencies:
      zone.js: "*"
  "@angular/core@*":
    dependencies:
      "@angular/compiler": "18.2.14"
