nodeLinker: pnp
npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  jest-preset-angular@*:
    dependencies:
      zone.js: "^0.14.0"
  "@angular/core@*":
    dependencies:
      "@angular/compiler": "^18.2.0"
