import { AbstractRenderer } from '@touchspin/core/renderer';
declare class Bootstrap5Renderer extends AbstractRenderer {
    private readonly initialInputGroup;
    private opts;
    private prefixEl;
    private postfixEl;
    private formControlAdded;
    wrapper: HTMLElement | null;
    constructor(...args: ConstructorParameters<typeof AbstractRenderer>);
    init(): void;
    teardown(): void;
    private initializeOptions;
    private resetElementReferences;
    private ensureFormControlClass;
    private restoreFormControlClass;
    buildInputGroup(): HTMLElement;
    buildBasicInputGroup(): HTMLElement;
    buildAdvancedInputGroup(existingInputGroup: HTMLElement): HTMLElement;
    private createInputGroupWrapper;
    private appendElementsToWrapper;
    private insertWrapperAndInput;
    private positionInputWithinWrapper;
    private findInputInsertionPoint;
    private findVerticalInsertionPoint;
    private findHorizontalInsertionPoint;
    private insertElementsIntoExistingGroup;
    private createButton;
    private createUpButton;
    private createDownButton;
    private createPrefixElement;
    private createPostfixElement;
    private createVerticalButtonWrapper;
    private buildClasses;
    private getButtonClass;
    private getButtonText;
    private detectInputGroupSize;
    private findInjectedElement;
    buildAndAttachDOM(): void;
    private storeElementReferences;
    private attachEventsToButtons;
    private registerSettingObservers;
    updatePrefix(value: string): void;
    updatePostfix(value: string): void;
    updateButtonClass(type: 'up' | 'down', className: string | null | undefined): void;
    updateVerticalButtonClass(type: 'up' | 'down', className: string | null | undefined): void;
    updateVerticalButtonText(type: 'up' | 'down', text?: string): void;
    updateButtonText(type: 'up' | 'down', text?: string): void;
    updatePrefixClasses(): void;
    updatePostfixClasses(): void;
    updateButtonFocusability(newValue: boolean): void;
    handleVerticalButtonsChange(_newValue: boolean): void;
    rebuildDOM(): void;
    private resetStateAfterRemoval;
    private resolveButtonLabel;
    private decodeHtml;
}
export default Bootstrap5Renderer;
//# sourceMappingURL=Bootstrap5Renderer.d.ts.map