name: CI Tests
run-name: Run Bootstrap TouchSpin Tests

on:
  push:
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable corepack (Yarn)
        run: corepack enable

      - name: Yarn install
        run: yarn install --immutable

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('.yarnrc.yml', 'yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers (chromium)
        run: npx playwright install chromium

      - name: Build all packages
        run: yarn build

      - name: Run tests (Chromium)
        run: yarn test

      - name: Validate tarballs (dry-run pack)
        run: |
          yarn workspaces foreach -A -v exec npm pack --dry-run

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: reports/
          retention-days: 7
